[compat]
texsmith = ">=0.6,<1.0"

[latex.template]
name = "recipe"
version = "0.1.0"
entrypoint = "template.tex"
engine = "lualatex"
texlive_year = 2023
tlmgr_packages = [
    "geometry",
    "fontspec",
    "pgf",
    "tabularx",
    "multirow",
    "xcolor",
]

[latex.template.assets]
"tikz-cookingsymbols.sty" = { source = "tikz-cookingsymbols.sty" }

[latex.template.slots.mainmatter]
default = true

[latex.template.attributes.preamble]
default = ""
type = "string"
allow_empty = true
