[compat]
texsmith = ">=0.1,<1.0"

[latex.template]
name = "snippet"
version = "0.1.4"
entrypoint = "template/template.tex"
engine = "lualatex"
shell_escape = false
texlive_year = 2023
tlmgr_packages = [
    "babel",
    "fontspec",
    "hyphenat",
    "microtype",
    "tcolorbox",
    "fontawesome5",
    "csquotes",
    "hyperref",
    "tikz",
]
fragments = [
    "ts-fonts",
    "ts-extra",
    "ts-keystrokes",
    "ts-callouts",
    "ts-code",
    "ts-todolist",
]

[latex.template.attributes.language]
default = "english"
type = "string"
allow_empty = false
sources = ["press.language", "language"]

[latex.template.attributes.width]
default = "12cm"
type = "string"
allow_empty = false
sources = ["press.snippet.width", "snippet.width", "width"]

[latex.template.attributes.margin]
default = "6mm"
type = "string"
allow_empty = false
sources = ["press.snippet.margin", "snippet.margin", "margin"]

[latex.template.attributes.dogear]
default = "5mm"
type = "string"
allow_empty = false
sources = ["press.snippet.dogear", "snippet.dogear", "dogear"]

[latex.template.attributes.border]
default = true
type = "boolean"
sources = ["press.snippet.border", "snippet.border", "border"]

[latex.template.slots.mainmatter]
default = true
depth = "section"
