site_name: TeXSmith
site_url: https://yves-chevallier.github.io/texsmith
site_author: Yves Chevallier
repo_name: yves-chevallier/texsmith
repo_url: https://github.com/yves-chevallier/texsmith
copyright: Copyright &copy; 2025 Yves Chevallier
theme:
  language: en
  name: material
  logo: assets/ts-anvil.svg
  font:
    text: Source Sans 3
  features:
    - search
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mike
  - awesome-nav
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            docstring_section_style: list
            show_docstring_description: true
            show_signature_annotations: true
            docstring_style: google
            separate_signature: true
            merge_init_into_class: true
  - pills
  - drawio:
      viewer_js: assets/drawio-viewer.js
  - texsmith:
      template: book
      build_dir: press
      embed_fragments: false
      books:
        - title: "TeXSmith Documentation"
          folder: texsmith-docs
          root: "__texsmith_full_navigation__"
          base_level: -1
          slots:
            preface: Home
          press:
            paragraph:
              indent: 0
              spacing: 0.5em
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yves-chevallier/texsmith
markdown_extensions:
  - abbr
  - admonition
  - texsmith.index
  - texsmith.texlogos
  - texsmith.smallcaps
  - texsmith.mermaid:
      base_paths:
        - !relative $config_dir/docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
      base_path: !relative $config_dir
  - pymdownx.blocks.html
  - pymdownx.blocks.caption
  - toc:
      permalink: true
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
extra_css:
  - css/brand.css
  - css/extra.css
exclude_docs: |
  assets/**/*.md
