[project]
name = "mkdocs-latex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "cairosvg>=2.8.2",
    "jinja2>=3.1.6",
    "mkdocs-material>=9.6.22",
    "pillow>=12.0.0",
    "pydantic>=2.7.0",
    "pypdf>=6.1.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "unidecode>=1.4.0",
    "typer>=0.12.5",
    "markdown>=3.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mkdocs_latex"]

[project.scripts]
mkdocs_latex = "mkdocs_latex.cli:main"

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "pytest>=8.4.2",
    "ruff>=0.14.1",
]

[tool.uv]
default-groups = ["dev"]
package = true

[tool.ruff]
extend-exclude = ["old-code-base"]

[tool.ruff.lint]
select = ["E", "F", "I"]   # E/F (pycodestyle/pyflakes) et I (isort)

[tool.ruff.lint.isort]
# options utiles
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["mkdocs_latex"]
section-order = ["future","standard-library","third-party","first-party","local-folder"]
lines-after-imports = 2
