[compat]
texsmith = ">=0.6,<1.0"

[latex.template]
name = "carauma-book"
version = "0.1.0"
entrypoint = "template/template.tex"
engine = "lualatex"
shell_escape = true
texlive_year = 2023
tlmgr_packages = [
    "microtype",
    "babel",
    "lettrine",
    "graphicx",
    "xcolor",
    "fontspec",
    "ebgaramond",
    "pgf",
    "geometry",
    "tocloft",
    "titlesec",
    "fancyhdr",
    "float",
    "booktabs",
    "tcolorbox",
    "minted",
]

[latex.template.attributes]
class_options = "12pt,openany"
title = "Título do Meu Livro"
subtitle = ""
author = "Janderson Gomes"
translator = ""
publisher = "Caraumã"
language = "brazilian"
contents_title = "Conteúdo"
edition_year = ""
edition_statement = ""
isbn = ""
bibliography = ""
bibliography_style = ""
copyright_year = ""
copyright_holder = ""
license_text = ""
preface_heading = "Prefácio"
preface_dropcap = ""
back_cover_text = ""
frontmatter = ""
backmatter = ""

[latex.template.slots.mainmatter]
default = true
depth = "chapter"

[latex.template.slots.frontmatter]
depth = "section"

[latex.template.slots.preface]
depth = "section"
strip_heading = true

[latex.template.slots.backmatter]
depth = "section"

[latex.template.assets]
"carauma-options.sty" = { source = "assets/carauma-options.sty" }
"logo-black.png" = { source = "assets/logo-black.png" }
"logo-white.png" = { source = "assets/logo-white.png" }
"frontmatter/titlepage.tex" = { source = "template/frontmatter/titlepage.tex", template = true }
"frontmatter/copyrightpage.tex" = { source = "template/frontmatter/copyrightpage.tex", template = true }
"frontmatter/preface.tex" = { source = "template/frontmatter/preface.tex", template = true }
"frontmatter/backpage.tex" = { source = "template/frontmatter/backpage.tex", template = true }
