[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "mkdocs-texsmith"
dynamic = ["version", "dependencies"]
description = "Convert MkDocs documentation to LaTeX PDF."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Yves Chevallier", email = "yves.chevalier@heig-vd.ch" }
]
keywords = [
    "extensions",
    "markdown",
    "latex",
    "texsmith",
    "mkdocs",
    "convert"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
[project.urls]
Homepage = "https://github.com/yves-chevallier/mkdocs-texsmith"

[project.entry-points."mkdocs.plugins"]
texsmith = "mkdocs_plugin_texsmith:LatexPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/mkdocs_plugin_texsmith"]

[tool.hatch.build]
exclude = [
    ".uv-cache",
    "build",
    "site",
]

[tool.hatch.version]
source = "vcs"
raw-options = { local_scheme = "no-local-version", root = "../.." }

[tool.hatch.metadata.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build.targets.sdist]
exclude = [
    ".uv-cache",
    "build",
    "site",
]

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-awesome-nav>=3.2.0",
    "mkdocs-material>=9.6.22",
    "mkdocs-pills>=0.1.0",
    "mkdocstrings-python>=1.18.2",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pillow>=12.0.0",
    "ruff>=0.14.1",
    "nox[pbs]>=2024.4.16",
]

[tool.uv]
default-groups = ["dev"]
package = true

[tool.uv.sources]
texsmith = { workspace = true }

[tool.ruff]
extend-exclude = ["site"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.ruff.lint.per-file-ignores]
"src/mkdocs_plugin_latex/cli.py" = ["B008"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["mkdocs_plugin_texsmith"]
section-order = ["future","standard-library","third-party","first-party","local-folder"]
lines-after-imports = 2
