[compat]
texsmith = ">=0.6,<1.0"

[latex.template]
name = "mdpi"
version = "0.1.0"
entrypoint = "template/template.tex"
engine = "lualatex"
shell_escape = true
texlive_year = 2023
tlmgr_packages = [
    "microtype",
    "hyperref",
    "geometry",
    "booktabs",
    "tcolorbox",
    "algorithms",
    "natbib",
    "cleveref",
    "listings",
    "luatex85",
]

[latex.template.attributes]
base_level = 1
class_options = "journal,article,submit,pdftex,moreauthors"
title = "Article Title"
title_citation = ""
short_title = ""
author = "John Doe"
abstract = ""
keywords = []
sections = []
affiliations = []
correspondence = []
acknowledgments = ""
funding = ""
conflicts = ""
data_availability = ""
journal = "journal"
stage = "submit"
manuscript_type = "article"
more_authors = true
bibliography = "References/references"
bibliography_style = ""

[latex.template.assets]
"Definitions" = { source = "assets/Definitions" }
".latexmkrc" = { source = "assets/latexmkrc" }
"texmf-cache" = { source = "assets/texmf-cache" }
