[compat]
texsmith = ">=0.6,<1.0"

[latex.template]
name = "els-cas"
version = "0.1.0"
entrypoint = "template/template.tex"
engine = "lualatex"
shell_escape = true
texlive_year = 2023
tlmgr_packages = [
    "fontspec",
    "hyperref",
    "microtype",
    "booktabs",
    "tcolorbox",
    "minted",
    "algorithms",
    "natbib",
]

[latex.template.attributes]
base_level = 1
column_mode = "double"
title = "Article Title"
short_title = ""
short_authors = ""
subtitle = ""
author = "John Doe"
date = "\\today"
abstract = ""
keywords = []
highlights = []
bibliography = "cas-refs"
bibliography_style = "cas-model2-names"
long_title = false

[latex.template.assets]
"cas-common.sty" = { source = "assets/cas-common.sty" }
"cas-dc.cls" = { source = "assets/cas-dc.cls" }
"cas-sc.cls" = { source = "assets/cas-sc.cls" }
"cas-refs.bib" = { source = "assets/cas-refs.bib" }
"cas-model2-names.bst" = { source = "assets/bst/cas-model2-names.bst" }
".latexmkrc" = { source = "assets/latexmkrc" }
