[compat]
texsmith = ">=0.6,<1.0"

[latex.template]
name = "book"
version = "0.1.0"
entrypoint = "template/template.tex"
engine = 'lualatex'
shell_escape = true
texlive_year = 2023
tlmgr_packages = [
    "babel",
    "babel-french",
    "csquotes",
    "fontspec",
    "fancyvrb",
    "geometry",
    "hyperref",
    "longtable",
    "microtype",
    "titlesec",
    "titletoc",
    "xcolor",
    "xunicode",
]
override = ["codeblock.tex", "codeinline.tex"]

[latex.template.attributes]
base_level = 0

title = "A LaTeX Book Template"
subtitle = "An example of a book template for MkDocs LaTeX"
author = "John Doe"
email = "john.doe@acme.corp"
date = "\\today"
language = "english"
cover = "circles"
glossary = false
listoffigures = true
listoftables = true

[latex.template.assets.covers]
source = "covers"

[latex.template.assets."covers/circles.tex"]
source = "covers/circles.tex"
template = true

[latex.template.assets."titlepage.tex"]
source = "titlepage.tex"

[latex.template.assets."imprint.tex"]
source = "imprint.tex"

[latex.template.assets."mkbook.cls"]
source = "template/mkbook.cls"
template = true
